version: '3.8'
services:
  model:
    build:
      context: ./model
    networks:
      - app-network

  drools:
    build:
      context: ./kjar
      dockerfile: Dockerfile
    depends_on:
      - model
    volumes:
      - ./model/src:/model/src  # Mount the model project's src directory into the drools project's container
    networks:
      - app-network

  app:
    build:
      context: ./service
    depends_on:
      - drools
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
    networks:
      - app-network
    ports:
      - "8080:8080"
    volumes:
      - ./model/src:/model/src  # Mount the model project's src directory into the service project's container
      - ./kjar/src:/kjar/src  # Mount the kjar project's src directory into the service project's container
      # You can add more volumes here if necessary

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
