package cep;

import com.ftn.sbnz.model.patient.Patient;
import com.ftn.sbnz.model.events.HeartBeatEvent;
import com.ftn.sbnz.model.events.ExstrasystoleEvent;
import com.ftn.sbnz.model.events.SAPEvent;
import com.ftn.sbnz.model.events.HypotensionEvent;
import com.ftn.sbnz.model.events.HypertensionEvent;
import com.ftn.sbnz.model.events.BradycardiaEvent;
import com.ftn.sbnz.model.events.TachycardiaEvent;


declare Alarm
    patientId: Long
    doctorId: Long
    message: String
end

declare VasopressorIV
    @role(event)
    @expires(16min)
    patientId: Long
end


rule "exstrasystole rule"
    when
        $patient : Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        Number(value >= 25) from accumulate(
            $exs: ExstrasystoleEvent(patientId == $id)
            over window: time(5m), count($exs)
        )
    then
        //предиктор срчаних компликација, алармирај лекара
        insert(new Alarm($id, $doctorId, "Detected more than 25 exstrasystoles in 5 minutes. Cardiovascular complications are possible."));
end

rule "tachycardia rule"
    when
        $patient: Patiner($id: id)
        Number(value > 80) from accumulate(
            $heartBeat: HeartBeatEvent(patientId == $id)
            over window: time(1m), count($heartBeat)
        )
    then
        //tahikardija
        insert(new TachycardiaEvent($id))
end

rule "tachycardia alarm"
    when 
        $patient: Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        exists(TachycardiaEvent(patientId == $id))
    then
        insert(new Alarm($id, $doctorId, "Detected tachycardia."));
end

rule "bradycardia rule"
    when
        $patient: Patient($id: id)
        Number(value < 60) from accumulate(
            $heartBeat: HeartBeatEvent(patientId == $id)
            over window: time(1m), count($heartBeat)
        )
    then
        //bradikardija
        insert(new BradycardiaEvent($id))    
end

rule "bradycardia alarm"
    when 
        $patient: Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        exists(BradycardiaEvent(patientId == $id))
    then
        insert(new Alarm($id, $doctorId, "Detected bradycardia."));
end

rule "hypertension rule"
    when
        $patient: Patient($id: id)
        Number(averageVal > 130 || (averageVal > ($patient.getBasalSAP() * 1.2))) from accumulate(
            $sap: SAPEvent(patientId == $id)
            over window: time(5m), average($sap.getValue())
        )
    then
        //hipertenzija
        insert(new HypertensionEvent($id));
end

rule "hypertension alarm rule"
    when
        $patient: Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        exists(HypertensionEvent(patientId == $id))
    then
        insert(new Alarm($id, $doctorId, "Detected hypertension."));
end

rule "hypotension rule"
    when
        $patient: Patient($id: id)
        Number(averageVal < 80 || (averageVal < ($patient.getBasalSAP() * 0.8))) from accumulate(
            $sap: SAPEvent(patientId == $id)
            over window: time(5m), average($sap.getValue())
        )
    then
        insert(new HypotensionEvent($id));
end

rule "hypotension alarm rule"
    when
        $patient: Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        Number(value == 2) from accumulate(
            $hypotension: HypotensionEvent(patientId == $id)
            over window: time(10m), count($hypotension)
        )
    then
        insert(new Alarm($id, $doctorId, "Detected hypotension. Cardiovascular complications are possible."));
end


// Post op
rule "Post op SAP - Crystalloids"
    when
        $patient: Patient($id: id)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        $averageVal: Number(intValue <= ($patient.getBasalSAP() - 20) && intValue >= ($patient.getBasalSAP() - 50))
        from accumulate(
            $sap: SAPEvent(patientId == $id) over window: time(5m),
            average($sap.getValue())
        )
    then
        System.out.println("Patient " + $patient.getFullname() + ": Initiate IV crystalloids and alert anesthesiologist.");
        insert(new Alarm($id, $doctorId, "Initiate IV crystalloids and alert anesthesiologist."));
       
end

rule "Post op SAP - Vasopressors Infusion"
    when
        $patient: Patient($id: id, $basalSAP: basalSAP)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        $averageVal: Number(intValue <= ($basalSAP - 50))
            from accumulate(
                $sap: SAPEvent(patientId == $id) over window: time(5m),
                average($sap.getValue())
            )
    then
        System.out.println("Patient " + $patient.getFullname() + ": Start vasopressors infusion.");
        insert(new Alarm($id, $doctorId, "Start vasopressors infusion."));
        insert(new VasopressorIV($id));
        
end

rule "Post op SAP - Vasopressors IV still low"
    when
        $patient: Patient($id: id, $basalSAP: basalSAP)
        $procedure: Procedure(patientId == $id, $doctorId: medicalStaffId)
        $vasopressorIV: VasopressorIV(patientId == $id)
        $SAPEvent: SAPEvent(this after[15min] $vasopressorIV, patientId == $id, $value <= ($basalSAP - 50))
    then
        System.out.println("Patient " + $patient.getFullname() + ": determine hemoglobin.");
        insert(new Alarm($id, $doctorId, "Determine hemoglobin."));
        
end

rule "Post op SAP - Inc"
    when
        $patient: Patient($id: id)
        $averageVal: Number(intValue >= ($patient.getBasalSAP() + 20) && intValue <= ($patient.getBasalSAP() + 50))
        from accumulate(
            $sap: SAPEvent(patientId == $id) over window: time(5m),
            average($sap.getValue())
        )
    then
        System.out.println("Patient " + $patient.getFullname() + ": бол, делиријум, мучнина и повраћање, плитко дисање.");
        // Todo add alert
end

rule "Post op SAP - Inc 50"
    when
        $patient: Patient($id: id, $basalSAP: basalSAP)
        $averageVal: Number(intValue >= ($basalSAP + 50))
            from accumulate(
                $sap: SAPEvent(patientId == $id) over window: time(5m),
                average($sap.getValue())
            )
    then
        System.out.println("Patient " + $patient.getFullname() + ": дати хипертензив.");
        // Todo add alert
end