package backward;

import com.ftn.sbnz.model.illness.PatientHistory;

query hasHeartProblems(long id)
    PatientHistory(idPatient == id, hasHeartIssues == true)
end

query ancestorHasHeartProblems(long id)
    PatientHistory(idPatient == id, $motherId : idMother, $fatherId : idFather)
    or ( hasHeartProblems($motherId;) )
    or ( hasHeartProblems($fatherId;) )
end

query familyHasHeartProblems(long id)
    hasHeartProblems(id;)
    or ( ancestorHasHeartProblems(id;) )
end