package diagnosis;

import com.ftn.sbnz.model.patient.Patient;
import com.ftn.sbnz.model.procedure.Procedure;
import com.ftn.sbnz.model.events.SymptomEvent;
import com.ftn.sbnz.model.illness.Illness;
import java.time.LocalDateTime;


rule "Bronchospasm"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id, procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id, procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Wheezing))
    then
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.BRONCHOSPASM));
        }
        System.out.println("Bronchospasm detected");
end

rule "Pneumonia"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id, procedureId == $procedureId,symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Fever))
    then
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.PNEUMONIA));
        }
        System.out.println("Pneumonia detected");
end

rule "Tension pneumothorax"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id, procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypotension))
        exists(SymptomEvent(patientId == $id, procedureId == $procedureId, symptom == SymptomEvent.Symptom.AbsentBreathSounds))
    then
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.TENSION_PNEUMOTHORAX));
        }
        System.out.println("Tension pneumothorax detected");
end

rule "Pulmonary tromboembolism"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypotension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Cyanosis))
    then
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.PULMONARY_TROMBOEMBOLISM));
        }
        System.out.println("Pulmonary tromboembolism detected");
end


rule "Heart failure - hypotension"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypotension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.PulmonaryEdema))
    then
        System.out.println("Heart failure detected");

        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.HEART_FAILURE));
        }
        modify($p) {
            setHasHearthFailure(true);
        }
end

rule "Heart failure - hypertension"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypertension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.PulmonaryEdema))
    then
        System.out.println("Heart failure detected");
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.HEART_FAILURE));
        }
        modify($p) {
            setHasHearthFailure(true);
        }
end

rule "Myocardial infarction - hypotension"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypotension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.ChestPain))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Arythmia))

    then
        System.out.println("Myocardial infarction detected");

        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.MYOCARDIAL_INFARCTION));
        }
        modify($p) {
            setHadHearthAttack(true);
        }
end

rule "Myocardial infarction - hypertension"
    when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypertension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.ChestPain))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Arythmia))

    then
        System.out.println("Myocardial infarction detected");
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.MYOCARDIAL_INFARCTION));
        }
        modify($p) {
            setHadHearthAttack(true);
        }
end

rule "Respiratory insuficiency"
     when
        $p : Patient($id: id)
        $procedure: Procedure(patientId == $id, $procedureId: id)
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Dyspnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachypnea))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypoxemia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Tachycardia))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Hypertension))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Cyanosis))
        exists(SymptomEvent(patientId == $id,procedureId == $procedureId, symptom == SymptomEvent.Symptom.Bradypnea))
    then
    
        modify($p) {
            addIllness(new Illness(LocalDateTime.now(), Illness.IllnessName.RESPIRATORY_INSUFICIENCY));
        }
        System.out.println("Respiratory insuficiency detected");

end


